title: Architect theme
description: Architect is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
repository: Dragon-wxl/note
github_url:https: https://github.com/Dragon-wxl
url: https://dragon-wxl.github.io
